products:
  items:
    - name: "Business Current Account"
      productCode: "BCA"
      features:
        schufa: true
        accountOpening: true
        pinActivation: true
        onlineBankingActivation: true
    - name: "Flex Funds"
      productCode: "FF"
      features:
        schufa: true
        accountOpening: true
        pinActivation: false
        onlineBankingActivation: true
    - name: "Deposits"
      productCode: "DEP"
      features:
        schufa: true
        accountOpening: true
        pinActivation: false
        onlineBankingActivation: false
    - name: "Savings"
      productCode: "SAV"
      features:
        schufa: true
        accountOpening: true
        pinActivation: true
        onlineBankingActivation: true
    - name: "Dummy"
      productCode: "DEF"
      features:
        schufa: true
        accountOpening: false
        pinActivation: false
        onlineBankingActivation: false
